// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_hrQg_N0m14XksXc1_AGId_tsVkzPzc',
    appId: '1:1045025384818:web:41817044ea24264ccc55eb',
    messagingSenderId: '1045025384818',
    projectId: 'mercados-tycoon',
    authDomain: 'mercados-tycoon.firebaseapp.com',
    storageBucket: 'mercados-tycoon.firebasestorage.app',
    measurementId: 'G-34ETZDDB8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoW9sJEvuQ5K_3B3UxsZsO0USFgHjfHRA',
    appId: '1:1045025384818:android:b4359f2eb5fdf549cc55eb',
    messagingSenderId: '1045025384818',
    projectId: 'mercados-tycoon',
    storageBucket: 'mercados-tycoon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkjuXYFWoj9YSl-A5BfXAo828wJSJaUcU',
    appId: '1:1045025384818:ios:d8cb08efc98b71f4cc55eb',
    messagingSenderId: '1045025384818',
    projectId: 'mercados-tycoon',
    storageBucket: 'mercados-tycoon.firebasestorage.app',
    androidClientId: '1045025384818-cct3qtlrthvrhqt1ed0v388fibabpm1d.apps.googleusercontent.com',
    iosClientId: '1045025384818-2hicqgu371jq230etpb7bvof0o9s9n1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.industrialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkjuXYFWoj9YSl-A5BfXAo828wJSJaUcU',
    appId: '1:1045025384818:ios:d8cb08efc98b71f4cc55eb',
    messagingSenderId: '1045025384818',
    projectId: 'mercados-tycoon',
    storageBucket: 'mercados-tycoon.firebasestorage.app',
    androidClientId: '1045025384818-cct3qtlrthvrhqt1ed0v388fibabpm1d.apps.googleusercontent.com',
    iosClientId: '1045025384818-2hicqgu371jq230etpb7bvof0o9s9n1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.industrialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR_hrQg_N0m14XksXc1_AGId_tsVkzPzc',
    appId: '1:1045025384818:web:5f3288bfae2256b5cc55eb',
    messagingSenderId: '1045025384818',
    projectId: 'mercados-tycoon',
    authDomain: 'mercados-tycoon.firebaseapp.com',
    storageBucket: 'mercados-tycoon.firebasestorage.app',
    measurementId: 'G-KBQN8W7YGL',
  );
}
